### PR TITLE
Fixes terraform depreciation on vpc -> domain #421

### LINKED ISSUE #421: fix terraform depreciation on vpc -> domain
Screenshot 2024-02-06 at 10 08 39

### PR DESCRIPTION
**Pull request by BreakingPitt**
# Pull Request

## Description

This pull request to address a deprecation warning related to the usage of the vpc attribute in the aws_eip resource, the warning suggests using the domain attribute instead.

**Changes Made:**

- Replaced _vpc = "true"_ in _aws_eip_ resource, using _domain = "vpc"_

**Why this is needed:**

The pull request aims to update the Terraform code to align with the latest recommendations and resolve the deprecation warning.

Please review the changes, and if everything looks good, feel free to merge it. If you have any questions or concerns, please don't hesitate to reach out.

Thanks,
Pedro

Fixes #421 

## Checklist:

- [*] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [*] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [*] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks @BreakingPitt for these
@all-contributors please add @BreakingPitt for code

**Comment by peterdudfield** [comment]
I got an error - 
Screenshot 2024-02-13 at 16 25 05
, so ill switch this back

**Comment by BreakingPitt** [comment]
Hi @peterdudfield 

Maybe you have to update the required_provider used on this code.

Can you check your AWS provider version? I've read that this changes on version 4.67.0, the next version of the provider 5.0.0 should allow the use of domain ="vpc".

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/nowcasting/development/backend.tf#L14,

**Pull request merged**
