### PR TITLE
add storage_type gp3 for rds database

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

Add gp3 storage type on pv sites database

## How Has This Been Tested?

Simon checks this manually and it improved the database

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by simlmx** [comment]
Look at the IOPS and latency charts in AWS.
If latency is high and IOPS seemed capped, then you should see a massive improvement by switching to `gp3`.
RDS_Management_Console
RDS_Management_Console

**Review by simlmx — APPROVED** [review]
LGTM

**Comment by simlmx** [comment]
@peterdudfield Do you think we need to specify [`storage_throughput`][1] or [`iops`][2]?
Those were set by default when I changed it to `gp3`.

RDS_Management_Console

Also, we should use an ["aws_db_parameter_group"][3] to set the postgresql configuration option `random_page_cost=1.1`. This basically tells postgresql that reading from the storage is quick and it can use that information to optimize queries further. In practice I saw a big improvement for the queries we are using.
I'm not sure how to add this in Terraform though.

[1]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage_throughput
[2]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#iops
[3]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group

**Comment by peterdudfield** [comment]
> @peterdudfield Do you think we need to specify [`storage_throughput`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage_throughput) or [`iops`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#iops)? Those were set by default when I changed it to `gp3`.
> 
> RDS_Management_Console
> 
> Also, we should use an ["aws_db_parameter_group"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group) to set the postgresql configuration option `random_page_cost=1.1`. This basically tells postgresql that reading from the storage is quick and it can use that information to optimize queries further. In practice I saw a big improvement for the queries we are using. I'm not sure how to add this in Terraform though.

Ive put this in another issue, if thats ok

**Comment by peterdudfield** [comment]
Currently got this error
Screenshot 2023-03-10 at 10 27 05

**Comment by peterdudfield** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/27702

here's says need to uprade [v4.45.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v4.45.0/CHANGELOG.md)

**Pull request merged**
