### PR TITLE
add diagrams

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

Add diagram how to clients can send PV data
Screenshot 2023-10-05 at 18 54 15
Screenshot 2023-10-05 at 18 54 11

## How Has This Been Tested?

looked at markdown locally

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by zakwatts** [comment]
Dont want to be annoying but is there any actual difference between database and db here?

Also maybe a link between the rest api and back to the client as well as the UI?

**Comment by dantravers** [comment]
Thanks.  Are some users more likely to use which scenario?

**Comment by peterdudfield** [comment]
> Dont want to be annoying but is there any actual difference between database and db here?
> 
> Also maybe a link between the rest api and back to the client as well as the UI?

both good points, ill add these points

**Comment by peterdudfield** [comment]
> Thanks. Are some users more likely to use which scenario?

I'm not sure. I think 1 is more likely, but we will have to see

**Comment by peterdudfield** [comment]
Ill add a third digaram which is a bit of mixtuire

https://docs.google.com/presentation/d/1mm5JAaNpulQoekZuynDZUmk4pf1osQPp-LdXsuPpghU/edit#slide=id.g288c353ee51_0_0

Screenshot 2023-10-06 at 09 35 48

**Comment by peterdudfield** [comment]
> Dont want to be annoying but is there any actual difference between database and db here?
> 
> Also maybe a link between the rest api and back to the client as well as the UI?

yea, hopefully the double arrow ends imply that

**Pull request merged**
